package com.scaleunlimited.flinkcrawler.sources;

import org.apache.flink.api.java.tuple.Tuple0;
import org.apache.flink.streaming.api.functions.source.SourceFunction;

/**
 * Generate an empty (Tuple0) tuple every X milliseconds. This gets
 * connected with other "real" streams and used (via a CoFlatMap function)
 * to trigger any results that have asynchronously been generated by the
 * multi-threaded operator running in the function.
 *
 */
@SuppressWarnings("serial")
public class TickleSource implements SourceFunction<Tuple0> {

	private boolean _keepRunning = false;
	
	public TickleSource() {
	}

	@Override
	public void cancel() {
		_keepRunning = false;
	}

	@Override
	public void run(SourceContext<Tuple0> context) throws Exception {
		_keepRunning = true;
		
		while (_keepRunning) {
			context.collect(new Tuple0());
			Thread.sleep(100L);
		}
	}

}
